export const BtnData = [
  { name: "Great for groups" },
  { name: "Family-friendly" },
  { name: "Anmials" },
  { name: "Arts & writing" },
  { name: "Baking" },
  { name: "Cooking" },
  { name: "Dance" },
  { name: "Drinking" },
  { name: "Entertainment" },
  { name: "Fitness" },
  { name: "History & Culture" },
  { name: "Magic" },
  { name: "Music" },
  { name: "Social Impact"},
  { name: "Welness" },
  { name: "Olympians & Paralympians" },
  { name: "Designed for accesibility" },
];
